baseURL = "https://junghanacs.github.io"
title = "Junghanacs's Home"
author = "Junghan Kim"
copyright = "Junghanacs"
paginate = 10 # for demonstration of pagination
languageCode = "ko"
defaultContentLanguage = "ko"
enableInlineShortcodes = true
languageName = "Korean"
languageCodeCountry = "kr"
timeZone = "Asia/Seoul"
hasCJKLanguage = true

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
theme = "tailwind"

[markup]
  _merge = "deep"

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
  [privacy.twitter]
    disabled = true
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = true
    simple = true
  [privacy.vimeo]
    disabled = true
    simple = true
