baseURL = "https://junghanacs.github.io"
title = "Junghanacs's Home"
author = "Junghan Kim"
copyright = "Junghan Kim"
paginate = 10 # for demonstration of pagination
languageCode = "ko"
defaultContentLanguage = "ko"
enableInlineShortcodes = true
languageName = "Korean"
languageCodeCountry = "kr"
timeZone = "Asia/Seoul"
hasCJKLanguage = true
enableEmoji = true
enableRobotsTXT = true
Toc = false
dateFormat = "2006-01-02"

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
theme = "hugo-theme-tailwind"

# https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
defaultMarkdownHandler = "goldmark"
_merge = "deep" # Important
  [markup.tableOfContents]
  endLevel = 3
  ordered = false
  startLevel = 2
  [markup.goldmark]
    [markup.goldmark.extensions]
      taskList = true
      definitionList = true
      footnote = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      [markup.goldmark.extensions.cjk]
        enable = true
        eastAsianLineBreaks = false # Important
        # 아래 설정의 의미는?
        # escapedSpace = true
        # eastAsianLineBreaksStyle = 'simple'
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderer]
        hardWraps= false # true => fill-column 80
        unsafe = true  # Enable user to embed HTML snippets in Markdown content.

[taxonomies]
series = "series"
category = "categories"
tag = "tags"

[privacy]
  [privacy.youtube]
    disabled = false
    privacyEnhanced = true
  [privacy.twitter]
    disabled = true
    enableDNT = true
    simple = true
  [privacy.instagram]
    disabled = true
    simple = true
  [privacy.vimeo]
    disabled = true
    simple = true
