[ko]
  languageCode = 'ko'
  languageDirection = 'ltr'
  languageName = 'Korean'
  weight = 1
  [ko.menu]
  [[ko.menu.main]]
    identifier = "post"
    name = "Posts"
    pageRef = "post"
    weight = 10
  [[ko.menu.main]]
    identifier = "config"
    name = "Configs"
    pageRef = "config"
    weight = 20
  [[ko.menu.main]]
    identifier = "weekly"
    name = "Weekly"
    pageRef = "weekly"
    weight = 30
  [[ko.menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "about"
    weight = 40
  [[ko.menu.main]]
    identifier = "test"
    name = "Test"
    pageRef = "test"
    weight = 50
  # [[ko.menu.main]]
  #   identifier = "rss"
  #   name = "RSS"
  #   url = "/index.xml"
  #   weight = 50

[en]
  languageCode = 'en-US'
  languageDirection = 'ltr'
  languageName = 'English'
  weight = 2 
  [en.menu]
  [[en.menu.main]]
    identifier = "post"
    name = "Post"
    pageRef = "post"
    weight = 10
  [[en.menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "about"
    weight = 20

# [zh-cn]
#   languageCode = 'zh-CN'
#   languageDirection = 'ltr'
#   languageName = '中文'
#   weight = 2
#   [zh-cn.menu]
#   [[zh-cn.menu.main]]
#     identifier = "post"
#     name = "文章"
#     pageRef = "post"
#     weight = 10

#   [[zh-cn.menu.main]]
#     identifier = "about"
#     name = "关于"
#     pageRef = "about"
#     weight = 20
