[ko]
  languageCode = 'ko'
  languageDirection = 'ltr'
  languageName = 'Korean'
  weight = 1
  [ko.menu]
  [[ko.menu.main]]
    identifier = "posts"
    name = "Posts"
  #  url = "/"
    pageRef = "posts"
    weight = 10
  # [[ko.menu.main]]
  #   identifier = "archives"
  #   name = "Archive"
  #   url = "/archives"
  #   weight = 20
  [[ko.menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 100

  # [[ko.menu.main]]
  #   identifier = "emacs"
  #   name = "Emacs"
  #   pageRef = "/categories/emacs/"
  #   weight = 30
  # [[ko.menu.main]]
  #   identifier = "weekly"
  #   name = "Weekly"
  #   pageRef = "/series/weekly/"
  #   weight = 30
  # [[ko.menu.main]]
  #   identifier = "tags"
  #   name = "Tags"
  #   pageRef = "tags"
  #   weight = 60
  # [[ko.menu.main]]
  #   identifier = "rss"
  #   name = "RSS"
  #   url = "/index.xml"
  #   weight = 99

[en]
  languageCode = 'en-US'
  languageDirection = 'ltr'
  languageName = 'English'
  weight = 2 
  [en.menu]
  [[en.menu.main]]
    identifier = "posts"
    name = "Posts"
    pageRef = "posts"
    weight = 10
  [[en.menu.main]]
    identifier = "about"
    name = "About"
    pageRef = "about"
    weight = 20

# [zh-cn]
#   languageCode = 'zh-CN'
#   languageDirection = 'ltr'
#   languageName = '中文'
#   weight = 2
#   [zh-cn.menu]
#   [[zh-cn.menu.main]]
#     identifier = "post"
#     name = "文章"
#     pageRef = "post"
#     weight = 10

#   [[zh-cn.menu.main]]
#     identifier = "about"
#     name = "关于"
#     pageRef = "about"
#     weight = 20
