# SEO keywords and description for your site.
keywords = "zettelkasten, second brain, emacs, writing to learn, digital minimalism"
subtitle = "Meditations on technology, learning, life, and text-editor"

math = true

# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "post"

[header]
  logo = "logo.webp"

[footer]
  since = 2022
  poweredby = true

# giscus is comments system powered by GitHub Discussions
# generate configurations from https://giscus.app/
[giscus]
  enabled = true
  repo = "junghanacs/junghanacs.github.io"
  repoID = "R_kgDOK99Lfg"
  category = "Announcements"
  categoryID = "DIC_kwDOK99Lfs4CcAvY"
  mapping = "pathname"
  strict = "0"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  lang = "ko"

[social_media]
  [[social_media.items]]
    enabled = true
    title = 'Github'
    icon = 'brand-github'
    link = 'https://github.com/junghanacs'

  [[social_media.items]]
    enabled = false
    title = 'Facebook'
    icon = 'brand-facebook'
    link = 'https://www.facebook.com/'

  [[social_media.items]]
    enabled = false
    title = 'Twitter'
    icon = 'brand-x'
    link = 'https://twitter.com/__PurPleFoX__'

  [[social_media.items]]
    enabled = false
    title = 'Instagram'
    icon = 'brand-instagram'
    link = 'https://www.instagram.com/'

  [[social_media.items]]
    enabled = false
    title = 'LinkedIn'
    icon = 'brand-linkedin'
    link = 'https://www.linkedin.com/'

