# GA Tracking ID
[googleAnalytics]
ID = "G-0003RSHTBC"

[instagram]
  disableInlineCSS = true

[twitter]
  disableInlineCSS = true

# comments
# https://gohugo.io/templates/internal/#disqus
# [disqus]
#   shortname = 'junghanacs'
