# GA Tracking ID
[googleAnalytics]
ID = "G-0003RSHTBC"

[instagram]
  disableInlineCSS = true

[twitter]
  disableInlineCSS = true

# comments
[disqus]
# https://gohugo.io/templates/internal/#disqus
# disqusShortname = "your-disqus-shortname"
  shortname = ''
